apiVersion: v1
kind: Secret
metadata:
  name: qa-toolbox-secrets
  namespace: qa-toolbox
type: Opaque
data:
  # Base64编码的敏感信息
  database-url: cG9zdGdyZXNxbDovL3FhX3VzZXI6cWFfcGFzc3dvcmRAcHJvZC1kYjo1NDMyL3FhX3Rvb2xib3g=  # postgresql://qa_user:qa_password@prod-db:5432/qa_toolbox
  redis-url: cmVkaXM6Ly9wcm9kLXJlZGlzOjYzNzkvMA==  # redis://prod-redis:6379/0
  jwt-secret: eW91ci1qd3Qtc2VjcmV0LWtleS1mb3ItcHJvZHVjdGlvbg==  # your-jwt-secret-key-for-production
  stripe-secret-key: c2tfbGl2ZV95b3VyX3N0cmlwZV9zZWNyZXRfa2V5  # sk_live_your_stripe_secret_key
  stripe-publishable-key: cGtfbGl2ZV95b3VyX3N0cmlwZV9wdWJsaXNoYWJsZV9rZXk=  # pk_live_your_stripe_publishable_key
