apps:
  - name: "QAToolBox Pro"
    id: "qa_toolbox"
    description: "工作效率工具套件"
    category: "productivity"
    icon: "Icons.work_outline"
    color: "AppTheme.primaryColor"
    features:
      - "测试用例生成器"
      - "PDF转换器"
      - "任务管理器"
      - "网络爬虫"
      - "代码分析工具"
      - "API测试工具"
      - "文档生成器"
      - "代码审查"
    dependencies:
      - "flutter_code_editor: ^0.2.0"
      - "pdf: ^3.10.7"
      - "http: ^1.1.0"
    service_port: "8010"
    service_dependencies:
      - "auth"
      - "user"
      - "analytics"
    metadata:
      target_users: ["开发者", "测试工程师", "产品经理"]
      ai_features: true
      enterprise_support: true

  - name: "LifeMode"
    id: "life_mode"
    description: "生活娱乐助手"
    category: "lifestyle"
    icon: "Icons.home_outlined"
    color: "AppTheme.secondaryColor"
    features:
      - "食物随机器"
      - "生活日记"
      - "冥想指南"
      - "旅行指南"
      - "音乐治疗"
      - "情绪日记"
      - "生活目标"
      - "时间胶囊"
    dependencies:
      - "audioplayers: ^5.2.1"
      - "image_picker: ^1.0.4"
      - "geolocator: ^10.1.0"
    service_port: "8011"
    service_dependencies:
      - "auth"
      - "user"
      - "analytics"
    metadata:
      target_users: ["生活达人", "美食爱好者"]
      ai_features: true
      location_based: true

  - name: "FitTracker"
    id: "fit_tracker"
    description: "健康管理平台"
    category: "health"
    icon: "Icons.fitness_center"
    color: "AppTheme.successColor"
    features:
      - "健身中心"
      - "BMI计算器"
      - "营养计算器"
      - "签到日历"
      - "运动追踪"
      - "训练计划"
      - "健康监测"
      - "社区互动"
    dependencies:
      - "pedometer: ^3.0.0"
      - "health: ^10.0.0"
      - "charts_flutter: ^0.12.0"
    service_port: "8012"
    service_dependencies:
      - "auth"
      - "user"
      - "analytics"
    metadata:
      target_users: ["健身爱好者", "健康管理用户"]
      ai_features: true
      health_data: true

  - name: "SocialHub"
    id: "social_hub"
    description: "社交互动中心"
    category: "social"
    icon: "Icons.people_outline"
    color: "AppTheme.warningColor"
    features:
      - "心链系统"
      - "搭子活动"
      - "社交订阅"
      - "聊天系统"
      - "人际关系管理"
      - "社交分析"
      - "活动推荐"
      - "社交游戏"
    dependencies:
      - "socket_io_client: ^2.0.3+1"
      - "camera: ^0.10.5+5"
      - "agora_rtc_engine: ^6.2.6"
    service_port: "8013"
    service_dependencies:
      - "auth"
      - "user"
      - "analytics"
      - "notification"
    metadata:
      target_users: ["社交活跃用户", "寻找伙伴的用户"]
      ai_features: true
      real_time: true

  - name: "CreativeStudio"
    id: "creative_studio"
    description: "创作工具套件"
    category: "creative"
    icon: "Icons.brush_outlined"
    color: "AppTheme.infoColor"
    features:
      - "创意写作"
      - "故事板"
      - "头像生成器"
      - "吉他训练"
      - "内容创作"
      - "设计工具"
      - "音乐制作"
      - "创作社区"
    dependencies:
      - "flutter_tts: ^3.8.5"
      - "image: ^4.1.3"
      - "audioplayers: ^5.2.1"
    service_port: "8014"
    service_dependencies:
      - "auth"
      - "user"
      - "analytics"
    metadata:
      target_users: ["创作者", "艺术家", "音乐爱好者"]
      ai_features: true
      media_processing: true
