name: social_hub
description: SocialHub - 社交互动平台
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # 状态管理
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # 网络请求
  dio: ^5.4.0
  retrofit: ^4.0.3
  
  # 本地存储
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI组件
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.0
  
  # 路由导航
  go_router: ^12.1.3
  
  # 工具库
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  logger: ^2.0.2+1
  
  # 权限
  permission_handler: ^11.1.0
  
  # 图片处理
  image_picker: ^1.0.4
  
  # 文件处理
  file_picker: ^8.0.0+1
  
  # 二维码
  qr_flutter: ^4.1.0
  
  # 图表
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # 代码生成
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  retrofit_generator: ^8.0.4
  hive_generator: ^2.0.1
  
  # 测试
  mockito: ^5.4.4
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
